import * as fs from 'node:fs';
import * as path from 'node:path';
import { computeFirstCommitSha } from '@ccx/storage';

export async function runInit(cwd: string = process.cwd()): Promise<void> {
  const ccxDir = path.join(cwd, '.ccx');
  const tomlPath = path.join(ccxDir, 'project.toml');

  if (fs.existsSync(tomlPath)) {
    process.stderr.write(`.ccx/project.toml already exists at ${tomlPath}\n`);
    return;
  }

  const id = computeFirstCommitSha(cwd); // throws if not a git repo
  const name = path.basename(path.resolve(cwd));

  fs.mkdirSync(ccxDir, { recursive: true });
  const content =
    `# Generated by \`ccx init\`. Do not edit \`id\` by hand.\n` +
    `id = "${id}"\n` +
    `name = "${name}"\n`;
  fs.writeFileSync(tomlPath, content);
  process.stdout.write(`Wrote ${tomlPath}\n`);
}
